### 1. Loading the dataset

In [46]:
import pandas as pd
df = pd.read_csv('/kaggle/input/ted-talks/data.csv')

df.head()

,title,author,date,views,likes,link
0,Climate action needs new frontline leadership,Ozawa Bineshi Albert,December 2021,404000,12000,https://ted.com/talks/ozawa_bineshi_albert_cli...
1,The dark history of the overthrow of Hawaii,Sydney Iaukea,February 2022,214000,6400,https://ted.com/talks/sydney_iaukea_the_dark_h...
2,How play can spark new ideas for your business,Martin Reeves,September 2021,412000,12000,https://ted.com/talks/martin_reeves_how_play_c...
3,Why is China appointing judges to combat clima...,James K. Thornton,October 2021,427000,12000,https://ted.com/talks/james_k_thornton_why_is_...
4,Cement's carbon problem — and 2 ways to fix it,Mahendra Singhi,October 2021,2400,72,https://ted.com/talks/mahendra_singhi_cement_s...

In [47]:
df.tail()

,title,author,date,views,likes,link
5435,The best stats you've ever seen,Hans Rosling,February 2006,15000000,458000,https://ted.com/talks/hans_rosling_the_best_st...
5436,Do schools kill creativity?,Sir Ken Robinson,February 2006,72000000,2100000,https://ted.com/talks/sir_ken_robinson_do_scho...
5437,Greening the ghetto,Majora Carter,February 2006,2900000,88000,https://ted.com/talks/majora_carter_greening_t...
5438,Simplicity sells,David Pogue,February 2006,2000000,60000,https://ted.com/talks/david_pogue_simplicity_s...
5439,Averting the climate crisis,Al Gore,February 2006,3600000,109000,https://ted.com/talks/al_gore_averting_the_cli...

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5440 entries, 0 to 5439
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   title   5440 non-null   object
 1   author  5439 non-null   object
 2   date    5440 non-null   object
 3   views   5440 non-null   int64
 4   likes   5440 non-null   int64
 5   link    5440 non-null   object
dtypes: int64(2), object(4)
memory usage: 255.1+ KB

In [49]:
df

,title,author,date,views,likes,link
0,Climate action needs new frontline leadership,Ozawa Bineshi Albert,December 2021,404000,12000,https://ted.com/talks/ozawa_bineshi_albert_cli...
1,The dark history of the overthrow of Hawaii,Sydney Iaukea,February 2022,214000,6400,https://ted.com/talks/sydney_iaukea_the_dark_h...
2,How play can spark new ideas for your business,Martin Reeves,September 2021,412000,12000,https://ted.com/talks/martin_reeves_how_play_c...
3,Why is China appointing judges to combat clima...,James K. Thornton,October 2021,427000,12000,https://ted.com/talks/james_k_thornton_why_is_...
4,Cement's carbon problem — and 2 ways to fix it,Mahendra Singhi,October 2021,2400,72,https://ted.com/talks/mahendra_singhi_cement_s...
...,...,...,...,...,...,...
5435,The best stats you've ever seen,Hans Rosling,February 2006,15000000,458000,https://ted.com/talks/hans_rosling_the_best_st...
5436,Do schools kill creativity?,Sir Ken Robinson,February 2006,72000000,2100000,https://ted.com/talks/sir_ken_robinson_do_scho...
5437,Greening the ghetto,Majora Carter,February 2006,2900000,88000,https://ted.com/talks/majora_carter_greening_t...
5438,Simplicity sells,David Pogue,February 2006,2000000,60000,https://ted.com/talks/david_pogue_simplicity_s...
5439,Averting the climate crisis,Al Gore,February 2006,3600000,109000,https://ted.com/talks/al_gore_averting_the_cli...

In [50]:
arr = np.array(df['views'])

print('----- Views Analysis -----')
print('Minimun : ', np.min(arr))
print('Maximum : ', np.max(arr))
print('Total   : ', np.sum(arr))
print('Average : ', int(np.mean(arr)))
print('--------------------------')

----- Views Analysis -----
Minimun :  532
Maximum :  72000000
Total   :  11214973211
Average :  2061575
--------------------------

In [51]:
arr = np.array(df['likes'])

print('----- Likes Analysis -----')
print('Minimun : ', np.min(arr))
print('Maximum : ', np.max(arr))
print('Total   : ', np.sum(arr))
print('Average : ', int(np.mean(arr)))
print('--------------------------')

----- Likes Analysis -----
Minimun :  15
Maximum :  2100000
Total   :  340585435
Average :  62607
--------------------------

In [52]:
72000000

72000000

In [55]:
df[df['views'] == 72000000]

,title,author,date,views,likes,link
5436,Do schools kill creativity?,Sir Ken Robinson,February 2006,72000000,2100000,https://ted.com/talks/sir_ken_robinson_do_scho...

In [73]:
df[df['views'] > 50000000]

,title,author,date,views,likes,link
2958,Inside the mind of a master procrastinator,Tim Urban,February 2016,60000000,1800000,https://ted.com/talks/tim_urban_inside_the_min...
4084,Your body language may shape who you are,Amy Cuddy,June 2012,64000000,1900000,https://ted.com/talks/amy_cuddy_your_body_lang...
4605,The power of vulnerability,Brené Brown,June 2010,56000000,1700000,https://ted.com/talks/brene_brown_the_power_of...
4765,How great leaders inspire action,Simon Sinek,September 2009,57000000,1700000,https://ted.com/talks/simon_sinek_how_great_le...
5436,Do schools kill creativity?,Sir Ken Robinson,February 2006,72000000,2100000,https://ted.com/talks/sir_ken_robinson_do_scho...

In [76]:
df['view_to_like_ratio'] = df['views']/df['likes']
df.head()

,title,author,date,views,likes,link,view_to_like_ratio
0,Climate action needs new frontline leadership,Ozawa Bineshi Albert,December 2021,404000,12000,https://ted.com/talks/ozawa_bineshi_albert_cli...,33.666667
1,The dark history of the overthrow of Hawaii,Sydney Iaukea,February 2022,214000,6400,https://ted.com/talks/sydney_iaukea_the_dark_h...,33.437500
2,How play can spark new ideas for your business,Martin Reeves,September 2021,412000,12000,https://ted.com/talks/martin_reeves_how_play_c...,34.333333
3,Why is China appointing judges to combat clima...,James K. Thornton,October 2021,427000,12000,https://ted.com/talks/james_k_thornton_why_is_...,35.583333
4,Cement's carbon problem — and 2 ways to fix it,Mahendra Singhi,October 2021,2400,72,https://ted.com/talks/mahendra_singhi_cement_s...,33.333333

In [78]:
arr = np.array(df['view_to_like_ratio'])

print('----- Ratio Analysis -----')
print('Minimun : ', np.min(arr))
print('Maximum : ', np.max(arr))
print('Total   : ', np.sum(arr))
print('Average : ', int(np.mean(arr)))
print('--------------------------')

----- Ratio Analysis -----
Minimun :  30.3951367781155
Maximum :  36.4
Total   :  180146.4432242789
Average :  33
--------------------------

In [82]:
df[df['view_to_like_ratio'] < 31]

,title,author,date,views,likes,link,view_to_like_ratio
1071,Three stories of Scotland,Mackenzie Dalrymple,July 2019,11000,359,https://ted.com/talks/mackenzie_dalrymple_thre...,30.640669
1112,The importance of queer allyship in the classroom,Coby Everton,November 2019,10000,329,https://ted.com/talks/coby_everton_the_importa...,30.395137
1462,Solar energy can help put power back in the ha...,Scott Nguyen,April 2019,10000,326,https://ted.com/talks/scott_nguyen_solar_energ...,30.674847
1733,A brie(f) history of cheese,Paul S. Kindstedt,December 2018,11000000,358000,https://ted.com/talks/paul_s_kindstedt_a_brie_...,30.726257
1761,Cómo usar el arte de la fotografía para restau...,Alejandro Chaskielberg,November 2018,12000,389,https://ted.com/talks/alejandro_chaskielberg_c...,30.848329
2247,How we'll predict the next refugee crisis,Rana Novack,December 2017,12000,388,https://ted.com/talks/rana_novack_how_we_ll_pr...,30.927835
2248,8 steps to understanding information (and mayb...,Phil Tetlow,December 2017,10000,323,https://ted.com/talks/phil_tetlow_8_steps_to_u...,30.959752
2491,There's more to life than being happy,Emily Esfahani Smith,April 2017,11000000,357000,https://ted.com/talks/emily_esfahani_smith_the...,30.812325
2558,Why you should define your fears instead of yo...,Tim Ferriss,April 2017,10000000,325000,https://ted.com/talks/tim_ferriss_why_you_shou...,30.769231
2918,Why do cats act so weird?,Tony Buffington,April 2016,11000000,356000,https://ted.com/talks/tony_buffington_why_do_c...,30.898876
3137,Imagining a new future for health systems in A...,Mathieu Lamiaux,June 2015,10000,326,https://ted.com/talks/mathieu_lamiaux_imaginin...,30.674847